name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    name: run
    runs-on: ubuntu-latest  # Runs on a fresh Linux virtual machine

    steps:
      - name: run
        run: |
          ls
          ./script.sh
